import api from "../config/axios";
import { ToISO } from "../utils/date";

const authHeader = () => {
  const token = localStorage.getItem("token");
  if (!token) return { headers: {} };

  return { headers: { Authorization: `Bearer ${token}` } };
};

export interface LeaveBalanceInfo {
  id: string;
  employeeId: string;
  maxQuantity: string;
  totalQuantity: string;
  used: string;
}

export interface CreateWorkLeaveRequest {
  leaveType: string;
  reason: string;
  startDate: string;
  endDate: string;
  file?: File | null;
}

export interface WorkLeavePayload {
  id: string;
  employeeId: string;
  employeeName: string;
  companyProfileId: string;
  leaveType: string;
  startDate: string;
  endDate: string;
  used: number;
  maxQuantity: number;
  totalDay: number;
  reason: string;
  status: string;
  isAutoGenerated: boolean;
  files?: string;
}

export interface DataWorkLeave {
  count: number;
  data: WorkLeavePayload[];
}

class WorkLeaveService {
  private base = "work-leave";
  private baseManagement = "work-leave-management";
  async getLeaveBalance(employeeId: string): Promise<LeaveBalanceInfo> {
    const response = await api.get<LeaveBalanceInfo>(
      `${this.base}/leave-balance/${employeeId}`,
      authHeader()
    );
    return response.data;
  }

  async createWorkLeave(
    employeeId: string,
    payload: CreateWorkLeaveRequest
  ): Promise<WorkLeavePayload> {
    const formData = new FormData();
    formData.append("leaveType", payload.leaveType);
    formData.append("reason", payload.reason);

    // konversi ke ISO
    formData.append("startDate", ToISO(payload.startDate) ?? "");
    formData.append("endDate", ToISO(payload.endDate) ?? "");

    if (payload.file) {
      formData.append("file", payload.file);
    }

    const response = await api.post<WorkLeavePayload>(
      `${this.base}/${employeeId}/create`,
      formData,
      {
        ...authHeader(),
        headers: {
          ...authHeader().headers,
          "Content-Type": "multipart/form-data",
        },
      }
    );

    return response.data;
  }

  async getWorkLeaveHistory(employeeId: string): Promise<DataWorkLeave> {
    const response = await api.get<DataWorkLeave>(
      `${this.base}/history/${employeeId}`,
      authHeader()
    );
    return response.data;
  }

  async dataWorkLeave(): Promise<DataWorkLeave> {
    const response = await api.get<DataWorkLeave>(
      `${this.baseManagement}/data`,
      authHeader()
    );
    return response.data;
  }

  async approveOrReject(
    workLeaveId: string,
    status: "approved" | "rejected"
  ): Promise<WorkLeavePayload> {
    const response = await api.put<WorkLeavePayload>(
      `${this.baseManagement}/approved/${workLeaveId}`,
      { status },
      authHeader()
    );
    return response.data;
  }

  async detail(workLeaveId: string): Promise<WorkLeavePayload> {
    const response = await api.get<WorkLeavePayload>(
      `${this.baseManagement}/detail/${workLeaveId}`,
      authHeader()
    );
    return response.data;
  }
}

export default new WorkLeaveService();